Updating READMEs
wasmCloud/wasmcloud-otp pull request #201
Opened 2021-08-31 13:04 UTC by autodidaddict

Signed-off-by: Kevin Hoffman <autodidaddict@users.noreply.github.com>

2021-08-31 18:46 UTC, stevelr commented
that's the last time i try to edit something in the github ui

2021-08-31 18:47 UTC, stevelr approved these changes

2021-09-01 00:16 UTC, brooksmtownsend requested changes
A couple small changes, otherwise looks good. Perhaps in the future we can look into getting code coverage, latest release, etc badges in this repo

2021-09-01 00:16 UTC, brooksmtownsend commented on README.md
> +The dashboard web UI (often colloquially referred to as the _washboard_) is a **Phoenix** application that fits snugly atop the host core, providing real-time web access to a variety of information,
I think a note here, similar to the above, saying `you can find the dashboard under [wasmcloud host] (link) in this repository` would be helpful as it's not named dashboard

2021-09-01 00:16 UTC, brooksmtownsend commented on host_core/README.md
> +If instead you prefer to work from the production release, then consult our [installation]() guide for the exact instructions.
Installation should go to documentation here

2021-09-01 15:26 UTC, brooksmtownsend approved these changes

2021-09-01 15:29 UTC, merged