gracefully restart an actor's RPC supervisor
wasmCloud/wasmcloud-otp pull request #429
Opened 2022-06-29 20:39 UTC by connorsmith256

Signed-off-by: Connor Smith <connor@cosmonic.com>

2022-06-29 20:43 UTC, brooksmtownsend reviewed
With your testing, did this end up falling over in any way if you start an actor, stop an actor, and then attempt to start 100 actors simultaneously?

For best results, I'd love to know what happens if you do this with an actor from a file just to remove any time spent to download OCI bytes

2022-06-30 13:12 UTC, autodidaddict requested changes
Per discussion we decided that we wanted to modify `terminate_actor` such that it would both terminate the process _and_ delete the child spec from the parent.

2022-06-30 13:49 UTC, brooksmtownsend commented
Once this is released, let's cut 0.55.1 to fix the bug and also update the instructions in wasmcloud-dev-site to point to this version

2022-06-30 20:35 UTC, autodidaddict submitted a review, later dismissed

2022-07-01 13:30 UTC, brooksmtownsend submitted a review, later dismissed

2022-07-01 13:45 UTC, autodidaddict approved these changes

2022-07-01 16:21 UTC, autodidaddict approved these changes

2022-07-01 16:27 UTC, merged