style(web): add values column in link def table
wasmCloud/wasmcloud-otp pull request #470
Opened 2022-09-16 04:01 UTC by rovast

Signed-off-by: rovast <rovast@163.com>

Add a value column in the link definition table to check the definition information on the dashboard.

<img width="1771" alt="image" src="https://user-images.githubusercontent.com/9459488/190553756-d2de5611-cf84-436c-9b4a-f0f36a40b68b.png">

2022-09-16 13:34 UTC, brooksmtownsend requested changes
@rovast I really like the idea behind this PR, however I have practical concerns for displaying link values alongside the dashboard. For example, if you were to link an actor to a blobstore with AWS credentials, this is what it may look like
<img width="882" alt="image" src="https://user-images.githubusercontent.com/12040685/190651087-4cb710ef-8849-46fd-9714-8c1d31dc209f.png">

I think, practically, it will be really difficult to design a UI that can handle longer link values, especially the base64 or JSON encoded ones.

One thing I would support, though, is a button that allows you to copy link values to the clipboard. This way we don't have to design the UI for it and you can always retrieve link values if desired. 

Thoughts @autodidaddict / @connorsmith256 ?

2022-09-16 15:34 UTC, connorsmith256 commented
Agreed with your comments @brooksmtownsend

I'm interested in having a broader conversation about sensitive values in link defs, but for the time being a copy button might suffice

2022-09-18 07:22 UTC, rovast commented
Yes! That's really a good idea, and if the values map is empty, no copy button is shown.

<img width="1608" alt="image" src="https://user-images.githubusercontent.com/9459488/190890543-9777a405-b666-4e67-94dc-4e8889ff53ff.png">

2022-09-19 17:35 UTC, brooksmtownsend requested changes

2022-09-19 17:35 UTC, brooksmtownsend commented on wasmcloud_host/lib/wasmcloud_host_web/live/components/link_row_component.ex
> +      <td><%= if map_size(@values) > 0 do %><button class="btn btn-primary btn-sm id-monospace" type="button"
Just a nit, can this button be centered to keep it in the middle of the column?

2022-09-19 17:36 UTC, brooksmtownsend requested changes
Now that I'm looking at the screenshot, I actually think the values copy button should be alongside the actions since it's something you can do with the linkdef. Thoughts? It would be best if it also had that popover that showed the tooltip for "Copy Link Definition Values" as well

2022-09-20 02:14 UTC, rovast commented
1. move the copy value button to the action column

<img width="669" alt="image" src="https://user-images.githubusercontent.com/9459488/191151687-72df5c7d-2d56-49a3-9b56-b54a0b63383a.png">

2. add tooltip for both delete and copy button

<img width="623" alt="image" src="https://user-images.githubusercontent.com/9459488/191151858-492e018c-dd07-4244-b2a3-574a1c363d12.png">

2022-09-20 02:27 UTC, brooksmtownsend reviewed
This looks great! I'll test it first thing when I get on tomorrow AM.

@connorsmith256 @autodidaddict do you have any other thoughts here?

2022-09-21 13:26 UTC, brooksmtownsend approved these changes
Looks great!

2022-09-21 13:26 UTC, merged